apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authenticwrite


namePrefix: dev-

commonLabels:
  env: dev

replicas:
- count: 1
  name: backend
- count: 1
  name: frontend

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.authenticwrite.local
    - op: replace
      path: /spec/tls/0/hosts/0
      value: dev.authenticwrite.local
    - op: replace
      path: /spec/tls/0/secretName
      value: dev-authenticwrite-tls
  target:
    kind: Ingress
    name: authenticwrite

images:
- name: backend
  newName: ghcr.io/lakunzy7/authenticwrite/backend
  newTag: manual123
- name: frontend
  newName: ghcr.io/lakunzy7/authenticwrite/frontend
  newTag: manual123
- name: ghcr.io/lakunzy7/authenticwrite/backend
  newTag: dev
- name: ghcr.io/lakunzy7/authenticwrite/frontend
  newTag: dev
resources:
- ../../base
