---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: eshop
  namespace: eshop
spec:
  subscriptions:
    - image:
        repoURL: ghcr.io/lakunzy7/authenticwrite/backend
        imageSelectionStrategy: NewestBuild
    - image:
        repoURL: ghcr.io/lakunzy7/authenticwrite/frontend
        imageSelectionStrategy: NewestBuild
