---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: eshop
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: eshop
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/lakunzy7/multi-cluster-deployment.git
        - name: gitBranch
          value: main
        - name: imageRepo
          value: docker.io/dotnet/eshop
        - name: overlayPath
          value: eshop-config/overlays/dev
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: ${{ vars.gitBranch }}
                path: ./repo
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./repo/${{ vars.overlayPath }}
            images:
              - image: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "kargo: promote ${{ vars.imageRepo }} to dev"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: eshop-dev
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredCommitFromStep: commit
