apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authenticwrite

resources:
  - namespace.yaml
  - backend.yaml
  - frontend.yaml
  - configmap.yaml
  - ingress.yaml

commonLabels:
  app: authenticwrite
