apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eshop-staging
nameSuffix: -staging

resources:
  - ../../base

commonLabels:
  environment: staging

images:
  - name: docker.io/dotnet/eshop
    newTag: staging-latest

replicas:
  - name: catalog-api
    count: 2
  - name: basket-api
    count: 2
  - name: order-api
    count: 2
  - name: eshop-web
    count: 2

patches:
  - target:
      kind: ConfigMap
      name: eshop-config
    patch: |-
      - op: replace
        path: /data/ASPNETCORE_ENVIRONMENT
        value: Staging
      - op: replace
        path: /data/SERILOG_MINIMUM_LOG_LEVEL
        value: Information
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 2
      - op: replace
        path: /spec/maxReplicas
        value: 5
  - target:
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1
