apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eshop-dev
nameSuffix: -dev

resources:
  - ../../base

commonLabels:
  environment: dev

images:
  - name: docker.io/dotnet/eshop
    newTag: dev-latest

replicas:
  - name: catalog-api
    count: 1
  - name: basket-api
    count: 1
  - name: order-api
    count: 1
  - name: eshop-web
    count: 1

patches:
  - target:
      kind: ConfigMap
      name: eshop-config
    patch: |-
      - op: replace
        path: /data/ASPNETCORE_ENVIRONMENT
        value: Development
      - op: replace
        path: /data/SERILOG_MINIMUM_LOG_LEVEL
        value: Debug
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3
  - target:
      kind: PodDisruptionBudget
    patch: |-
      - op: replace
        path: /spec/minAvailable
        value: 1
