apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: authenticwrite
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
  - stage: staging
    autoPromotionEnabled: false

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: authenticwrite
  namespace: authenticwrite
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/lakunzy7/authenticwrite
      imageSelectionStrategy: SemVer
      allowTags: '^v\d+\.\d+\.\d+$'
      semverConstraint: '>= 0.0.1'
