apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- project.yaml
- warehouse-demo.yaml
- promotiontask.yaml
- dev-stage.yaml
- staging-stage.yaml
- prod-stage.yaml
- kargo-ing.yaml

sortOptions:
  order: fifo
