apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: authenticwrite
  annotations:
    kargo.akuity.io/color: lime
spec:
  subscriptions:
    upstreamStages:
    - name: dev
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/lakunzy7/multi-cluster-deployment.git
      writeBranch: main
      kustomize:
        images:
        - image: ghcr.io/lakunzy7/authenticwrite/backend
          path: kubernetes/overlays/staging
        - image: ghcr.io/lakunzy7/authenticwrite/frontend
          path: kubernetes/overlays/staging
