environment: dev

backend:
  image: ghcr.io/lakunzy7/authenticwrite/backend
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: "1Gi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "500m"

frontend:
  image: ghcr.io/lakunzy7/authenticwrite/frontend
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "250m"

imagePullSecrets:
  - name: ghcr-pull-secret

ingress:
  enabled: false
