apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: authenticwrite

bases:
  - ../../base

namePrefix: staging-

commonLabels:
  env: staging

replicas:
  - name: backend
    count: 2
  - name: frontend
    count: 2

patches:
  - target:
      kind: Ingress
      name: authenticwrite
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.authenticwrite.local
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging.authenticwrite.local
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-authenticwrite-tls

images:
  - name: ghcr.io/lakunzy7/authenticwrite/backend
    newTag: staging  # will be overridden by Kargo
  - name: ghcr.io/lakunzy7/authenticwrite/frontend
    newTag: staging  # will be overridden by Kargo
