kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: cloudopshub-local
networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true,node-role=control-plane"
    extraPortMappings:
      - containerPort: 80
        hostPort: 18080
        protocol: TCP
      - containerPort: 443
        hostPort: 18443
        protocol: TCP
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
  - role: worker
    labels:
      node-role: worker
      workload-type: applications
  - role: worker
    labels:
      node-role: worker
      workload-type: applications
