---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    name: k8slab-second-cluster
    namespace: argocd
spec:
    encryptedData:
        config: REPLACE_WITH_REALVALUE
        name: REPLACE_WITH_REALVALUE
        server: REPLACE_WITH_REALVALUE
    template:
        metadata:
            labels:
                argocd.argoproj.io/secret-type: cluster
            name: k8slab-second-cluster
            namespace: argocd
        type: Opaque
