---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: eshop
data:
  ASPNETCORE_ENVIRONMENT: Production
  SERILOG_MINIMUM_LOG_LEVEL: Information
  PODINFO_UI_MESSAGE: "hello from cloudopshub"
